# Generated by Django 2.2.12 on 2020-06-17 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_achievementpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationPost',
            fields=[
                ('cvpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cv.CVPost')),
            ],
            bases=('cv.cvpost',),
        ),
    ]
