# Generated by Django 2.2.12 on 2020-06-18 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_interestpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPost',
            fields=[
                ('cvpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cv.CVPost')),
                ('sub_title', models.CharField(max_length=100)),
            ],
            bases=('cv.cvpost',),
        ),
    ]
