# Generated by Django 2.2.12 on 2020-06-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_projectpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='image',
            field=models.ImageField(upload_to='cv/img/profile'),
        ),
    ]
