# Generated by Django 2.2.12 on 2020-06-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_auto_20200618_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='url',
            field=models.URLField(default=None, max_length=300),
        ),
    ]
