# Generated by Django 2.2.12 on 2020-06-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_projectpost_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
