# Generated by Django 2.2.12 on 2020-06-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_auto_20200618_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_pdf', models.FileField(upload_to='cv/pdf/cv')),
            ],
        ),
    ]
