# Generated by Django 2.2.12 on 2020-06-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_cvpdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementpost',
            name='sub_title',
        ),
    ]
