# Generated by Django 2.2.12 on 2020-06-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0018_educationpost_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationpost',
            name='body',
        ),
    ]
