# Generated by Django 2.2.12 on 2020-06-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0019_remove_educationpost_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddActivitiesPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='cvpost',
            name='text',
            field=models.TextField(default="<p class='cv-post-text'> </p>"),
        ),
    ]
