# Generated by Django 2.2.12 on 2020-07-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0020_auto_20200624_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bio',
        ),
        migrations.AlterField(
            model_name='addactivitiespost',
            name='text',
            field=models.TextField(default="<ul class='fa-ul cv-post-text'><li><i class='fa-li fa fa-users'></i> </li></ul>"),
        ),
        migrations.AlterField(
            model_name='skillpost',
            name='category',
            field=models.CharField(choices=[('LANGUAGES', 'Languages'), ('PROGRAMMING_LANGUAGES', 'Programming Languages'), ('OTHER_PROGRAMMING_SKILLS', 'Other Programming Skills')], default='PROGRAMMING_LANGUAGES', max_length=150),
        ),
    ]
