# Generated by Django 2.2.12 on 2020-07-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0021_auto_20200705_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
