# Generated by Django 5.0.1 on 2024-02-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0023_professionalengagementspost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievementpost',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='addactivitiespost',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='cvpost',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='educationpost',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='interestpost',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='professionalengagementspost',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='projectpost',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='qualificationpost',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='skillpost',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='workpost',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='addactivitiespost',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvpost',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interestpost',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpost',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillpost',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
