# Generated by Django 5.0.1 on 2024-02-05 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0024_alter_achievementpost_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProjectPost',
            fields=[
                ('cvpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cv.cvpost')),
                ('sub_title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=('cv.cvpost',),
        ),
    ]
